spring.datasource.url=${MYSQL_DEV_URL}
spring.datasource.username=${MYSQL_DEV_USERNAME}
spring.datasource.password=${MYSQL_DEV_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always // Puedes poner esto en never si no quieres que se ejecute el schema.sql y data.sql cada vez que inicies la aplicación
spring.jpa.defer-datasource-initialization=true  // Puedes poner esto en false si quieres que se ejecute el schema.sql y data.sql antes de que se inicialice el datasource
